# Generated by Django 3.0.3 on 2020-02-29 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200226_1020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logic',
            options={'ordering': ['created'], 'verbose_name_plural': 'Logic'},
        ),
    ]
