# Generated by Django 3.0.3 on 2020-04-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200411_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logic',
            old_name='js',
            new_name='script',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='js',
            new_name='assets',
        ),
        migrations.AddField(
            model_name='block',
            name='script',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='script',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='logic',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
