# Generated by Django 3.0.3 on 2020-04-14 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200413_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='project',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='main.Project'),
        ),
        migrations.AlterField(
            model_name='logic',
            name='project',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='main.Project'),
        ),
        migrations.AlterField(
            model_name='page',
            name='project',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='main.Project'),
        ),
    ]
