# Generated by Django 3.0.3 on 2020-04-15 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200414_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='style',
            new_name='styles',
        ),
    ]
