# Generated by Django 3.0.3 on 2020-04-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200415_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='fileType',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='size',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='url',
        ),
        migrations.AddField(
            model_name='asset',
            name='file',
            field=models.FileField(default='0', upload_to=''),
        ),
    ]
