# Generated by Django 3.0.3 on 2020-04-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200419_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='assets',
        ),
        migrations.RemoveField(
            model_name='block',
            name='components',
        ),
        migrations.RemoveField(
            model_name='block',
            name='styles',
        ),
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='branding',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='customDomain',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='customDomainUrl',
            field=models.URLField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='market',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='multipage',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='public',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='domain',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='published',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
