# Generated by Django 3.0.3 on 2020-05-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200429_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='active',
        ),
        migrations.RemoveField(
            model_name='order',
            name='expires',
        ),
        migrations.AddField(
            model_name='userdata',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userdata',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userdata',
            name='company',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userdata',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='plan',
            field=models.CharField(choices=[('HO', 'Hobbyist'), ('DV', 'Developer'), ('PR', 'Premium'), ('ET', 'Enterprise')], default='HO', max_length=2),
        ),
        migrations.AlterField(
            model_name='page',
            name='lastSaved',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='lastPublished',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
